### ISSUE TITLE
CLI Interface causes massive problems when required by tests

### ISSUE THREAD

**Issue by themetalone** [oasp/ts-merger#21]
After the tests were reworked the merger chrashes when requested by the test files. 

for some reasons the merger is invoked  with the test suites as arguments (following the stack trace this may be caused by the Module compiler). 

```
$ npm test

> ts-merger@1.0.0 test C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger
> mocha -r node_modules/ts-node/register.js ./test/*_test.ts

Called with args:strategy:false,base:node_modules/ts-node/register.js,patch:./test/class_decorator_test.ts,result:./test/class_field_test.ts,encoding./test/class_method_test.ts
Error: Unknown encoding: ./test/class_method_test.ts
    at assertEncoding (fs.js:88:11)
    at Object.fs.readFileSync (fs.js:427:3)
    at merge (C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\src\index.ts:53:61)
    at Object.<anonymous> (C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\src\index.ts:32:5)
    at Module._compile (module.js:425:26)
    at Module.m._compile (C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\node_modules\ts-node\src\index.ts:410:23)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\node_modules\ts-node\src\index.ts:413:12)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\test\class_decorator_test.ts:1:1)
    at Module._compile (module.js:425:26)
    at Module.m._compile (C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\node_modules\ts-node\src\index.ts:410:23)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\node_modules\ts-node\src\index.ts:413:12)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\node_modules\mocha\lib\mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\node_modules\mocha\lib\mocha.js:227:14)
    at Mocha.run (C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\node_modules\mocha\lib\mocha.js:495:10)
    at Object.<anonymous> (C:\Devon-dist_2.1.2\workspaces\ts-merger\ts-merger\node_modules\mocha\bin\_mocha:469:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
npm ERR! Test failed.  See above for more details.
```

**Comment by themetalone** [comment]
Current Idea is to use the https://www.npmjs.com/package/command-line-args package

**Comment by themetalone** [comment]
Cause was the way Mocha is called by npm combined with the way the merger parses the cli arguments
